---
jobs:
- name: container-bosh-staging
  plan:
  - in_parallel: &resources
    - get: cg-scripts
    - get: concourse-config
    - get: master-bosh-root-cert
  - task: jumpbox
    file: concourse-config/jumpbox-pages.yml
    params:
      CREDHUB_CA_CERT: master-bosh-root-cert/master-bosh.crt
      CREDHUB_CLIENT: ((staging-credhub-admin-client))
      CREDHUB_SECRET: ((staging-credhub-admin-secret))
      CREDHUB_SERVER: ((staging-credhub-api-server))
      PROMPT_COLOR: "2" # green
- name: container-bosh-production
  plan:
  - in_parallel: &resources
    - get: cg-scripts
    - get: concourse-config
    - get: master-bosh-root-cert
  - task: jumpbox
    file: concourse-config/jumpbox-pages.yml
    params:
      CREDHUB_CA_CERT: master-bosh-root-cert/master-bosh.crt
      CREDHUB_CLIENT: ((production-credhub-admin-client))
      CREDHUB_SECRET: ((production-credhub-admin-secret))
      CREDHUB_SERVER: ((production-credhub-api-server))
      PROMPT_COLOR: "1" # red


resources:
- name: concourse-config
  type: git
  source:
    uri: ((concourse-config-git-url))
    branch: main
    paths:
    - jumpbox-pages.yml
    - jumpbox-pages.sh

- name: master-bosh-root-cert
  type: s3-iam
  source:
    bucket: ((production-bucket-name))
    region_name: ((aws-region))
    versioned_file: master-bosh.crt

- name: cg-scripts
  type: git
  source:
    uri: https://github.com/cloud-gov/cg-scripts
    branch: main

resource_types:
- name: s3-iam
  type: docker-image
  source:
    repository: 18fgsa/s3-resource
