---
jobs:
- name: deploy-concourse-staging
  serial: true
  interruptible: true
  plan:
  - in_parallel:
    - get: concourse-deployment
      trigger: true
    - get: concourse-config
      trigger: true
    - get: terraform-yaml
    - get: concourse-stemcell-bionic
      trigger: true
  - put: concourse-staging-deployment
    params: &deploy-params
      manifest: concourse-deployment/cluster/concourse.yml
      stemcells:
      - concourse-stemcell-bionic/*.tgz
      ops_files:
      - concourse-deployment/cluster/operations/basic-auth.yml
      - concourse-deployment/cluster/operations/build-log-retention.yml
      - concourse-deployment/cluster/operations/scale.yml
      - concourse-deployment/cluster/operations/enable-global-resources.yml
      - concourse-config/operations/credhub.yml
      - concourse-config/operations/iaas-worker.yml
      - concourse-config/operations/postgres-staging.yml
      - concourse-config/operations/driver.yml
      - concourse-config/operations/config.yml
      - concourse-config/operations/generic-oauth.yml
      - concourse-config/operations/compliance.yml
      - concourse-config/operations/external-postgres-tls.yml
      - concourse-config/operations/prometheus.yml
      - concourse-config/operations/update-strategy.yml
      - concourse-config/operations/set-garbage-collection.yml
      - concourse-config/operations/base-resource-defaults.yml
      - concourse-config/operations/bosh-dns-aliases.yml
      - concourse-config/operations/use-bionic.yml
      vars_files:
      - concourse-deployment/versions.yml
      - concourse-config/variables/staging.yml
      - concourse-config/variables/postgres-tls.yml
      - terraform-yaml/state.yml
  - task: smoke-test
    file: concourse-config/ci/smoke-test.yml
    params:
      ATC_URL: https://ci.fr-stage.cloud.gov
      BASIC_AUTH_USERNAME: ((basic-auth-username-staging))
      BASIC_AUTH_PASSWORD: ((basic-auth-password-staging))
  - task: iptables-iaas-worker-bosh-dns
    config: &iptables-iaas-worker-bosh-dns
      container_limits: {}
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: 18fgsa/concourse-task
      params:
        BOSH_ENVIRONMENT: ((concourse-staging-deployment-bosh-target))
        BOSH_CLIENT: ci
        BOSH_CLIENT_SECRET: ((tooling_bosh_uaa_ci_client_secret))
        BOSH_CA_CERT: ((common_ca_cert_store))
        BOSH_DEPLOYMENT: concourse-staging
      run:
        path: sh
        args:
        - -exc
        - |
          bosh ssh iaas-worker "sudo sh -c 'iptables -D INPUT -s 10.80.0.0/16 -d 169.254.0.2/32 -p udp -m udp --dport 53 -j ACCEPT || true'"
          bosh ssh iaas-worker "sudo sh -c 'iptables -D INPUT -s 10.80.0.0/16 -d 169.254.0.2/32 -p tcp -m tcp --dport 53 -j ACCEPT || true'"
          bosh ssh iaas-worker "sudo sh -c 'iptables -I INPUT 1 -s 10.80.0.0/16 -d 169.254.0.2/32 -p udp -m udp --dport 53 -j ACCEPT'"
          bosh ssh iaas-worker "sudo sh -c 'iptables -I INPUT 1 -s 10.80.0.0/16 -d 169.254.0.2/32 -p tcp -m tcp --dport 53 -j ACCEPT'"
  - task: iptables-worker-bosh-dns
    tags: [iaas]
    config: &iptables-worker-bosh-dns
      container_limits: {}
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: 18fgsa/concourse-task
      params:
        BOSH_ENVIRONMENT: ((concourse-staging-deployment-bosh-target))
        BOSH_CLIENT: ci
        BOSH_CLIENT_SECRET: ((tooling_bosh_uaa_ci_client_secret))
        BOSH_CA_CERT: ((common_ca_cert_store))
        BOSH_DEPLOYMENT: concourse-staging
      run:
        path: sh
        args:
        - -exc
        - |
          bosh ssh worker "sudo sh -c 'iptables -D INPUT -s 10.80.0.0/16 -d 169.254.0.2/32 -p udp -m udp --dport 53 -j ACCEPT || true'"
          bosh ssh worker "sudo sh -c 'iptables -D INPUT -s 10.80.0.0/16 -d 169.254.0.2/32 -p tcp -m tcp --dport 53 -j ACCEPT || true'"
          bosh ssh worker "sudo sh -c 'iptables -I INPUT 1 -s 10.80.0.0/16 -d 169.254.0.2/32 -p udp -m udp --dport 53 -j ACCEPT'"
          bosh ssh worker "sudo sh -c 'iptables -I INPUT 1 -s 10.80.0.0/16 -d 169.254.0.2/32 -p tcp -m tcp --dport 53 -j ACCEPT'"
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy Concourse on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed Concourse on staging
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: set-teams-staging
  plan:
  - get: team-source
    params: {depth: 1}
    trigger: true
  - put: terraform
    params:
      env_name: staging
      terraform_source: team-source/teams
      vars:
        concourse_url: https://ci.fr-stage.cloud.gov
        concourse_username: ((basic-auth-username-staging))
        concourse_password: ((basic-auth-password-staging))

- name: deploy-concourse-production
  serial: true
  interruptible: true
  plan:
  - in_parallel:
    - get: concourse-deployment
      passed: [deploy-concourse-staging]
      trigger: true
    - get: concourse-config
      passed: [deploy-concourse-staging]
      trigger: true
    - get: terraform-yaml
    - get: concourse-stemcell-bionic
      trigger: true
      passed: [deploy-concourse-staging]
  - put: concourse-production-deployment
    params:
      <<: *deploy-params
      ops_files:
      - concourse-deployment/cluster/operations/build-log-retention.yml
      - concourse-deployment/cluster/operations/scale.yml
      - concourse-deployment/cluster/operations/enable-global-resources.yml
      - concourse-config/operations/iaas-worker.yml
      - concourse-config/operations/postgres-production.yml
      - concourse-config/operations/external-postgres-tls.yml
      - concourse-config/operations/driver.yml
      - concourse-config/operations/config.yml
      - concourse-config/operations/generic-oauth.yml
      - concourse-config/operations/compliance.yml
      - concourse-config/operations/prometheus.yml
      - concourse-config/operations/update-strategy.yml
      - concourse-config/operations/set-garbage-collection.yml
      - concourse-config/operations/base-resource-defaults.yml
      - concourse-config/operations/bosh-dns-aliases.yml
      - concourse-config/operations/use-bionic.yml
      vars_files:
      - concourse-deployment/versions.yml
      - concourse-config/variables/production.yml
      - concourse-config/variables/postgres-tls.yml
      - terraform-yaml/state.yml
  - task: iptables-iaas-worker-bosh-dns
    config:
      <<: *iptables-iaas-worker-bosh-dns
      params:
        BOSH_ENVIRONMENT: ((concourse-production-deployment-bosh-target))
        BOSH_CLIENT: ci
        BOSH_CLIENT_SECRET: ((tooling_bosh_uaa_ci_client_secret))
        BOSH_CA_CERT: ((common_ca_cert_store))
        BOSH_DEPLOYMENT: concourse-production
  - task: iptables-worker-bosh-dns
    tags: [iaas]
    config:
      <<: *iptables-worker-bosh-dns
      params:
        BOSH_ENVIRONMENT: ((concourse-production-deployment-bosh-target))
        BOSH_CLIENT: ci
        BOSH_CLIENT_SECRET: ((tooling_bosh_uaa_ci_client_secret))
        BOSH_CA_CERT: ((common_ca_cert_store))
        BOSH_DEPLOYMENT: concourse-production
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy Concourse on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))
  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: Successfully deployed Concourse on production
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

resources:
- name: concourse-deployment
  type: git
  source:
    uri: https://github.com/concourse/concourse-bosh-deployment
    branch: master
    tag_filter: v6.*

- name: concourse-config
  type: git
  source:
    uri: ((concourse-config-git-url))

- name: concourse-stemcell-bionic
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-bionic-go_agent

- name: concourse-production-deployment
  type: bosh-deployment
  source:
    target: ((concourse-production-deployment-bosh-target))
    client: ci
    client_secret: ((tooling_bosh_uaa_ci_client_secret))
    deployment: ((concourse-production-deployment-bosh-deployment))
    ca_cert: ((common_ca_cert_store))

- name: concourse-staging-deployment
  type: bosh-deployment
  source:
    target: ((concourse-staging-deployment-bosh-target))
    client: ci
    client_secret: ((tooling_bosh_uaa_ci_client_secret))
    deployment: ((concourse-staging-deployment-bosh-deployment))
    ca_cert: ((common_ca_cert_store))

- name: slack
  type: slack-notification-docker
  source:
    url: ((slack-webhook-url))

- name: terraform-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file))
    region_name: ((aws-region))

- name: team-source
  type: git
  source:
    uri: ((concourse-config-git-url))
    paths: [teams/*]

- name: terraform
  type: terraform
  source:
    backend_type: s3
    backend_config:
      bucket: ((aws_s3_tfstate_bucket))
      key: concourse/terraform.tfstate
      region: ((aws_s3_region))
      access_key: ((aws_s3_access_key_id))
      secret_key: ((aws_s3_secret_access_key))

resource_types:
- name: slack-notification-docker
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    registry_mirror:
      host: docker-registry-mirror.app.cloud.gov:443

- name: bosh-deployment
  type: registry-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    registry_mirror:
      host: docker-registry-mirror.app.cloud.gov:443

- name: s3-iam
  type: registry-image
  source:
    repository: 18fgsa/s3-resource
    registry_mirror:
      host: docker-registry-mirror.app.cloud.gov:443

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest
